import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>カレンダー</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>へっだー</header>

      <main>
        <p>Hello World!</p>
      </main>

      <footer>ふったー</footer>
      <style jsx>{`
        p {
          color: red;
        }
      `}</style>
    </div>
  );
};

export default Home;
